import { ArrowRight, CheckCircle2, ShieldCheck, Landmark, Scale, Calculator, MonitorCog, SearchCheck, Building2, Target, Eye, Gem } from 'lucide-react';
const services=[
['Internal Audit & Governance','Strengthening governance, internal controls, accountability and operational performance.',ShieldCheck],
['Asset Management','GRAP/IFRS compliant asset registers, verification, condition assessments, optimisation and training.',Building2],
['Budgeting & Municipal Finance','GRAP compliant budgeting, cash flow, reconciliations, annual financial statements and audit files.',Landmark],
['Enterprise Risk Management','Integrated risk management, risk infrastructure, enterprise risk assessments and awareness training.',Target],
['Investigations & Compliance','Forensic investigations, irregular expenditure investigations and regulatory compliance reviews.',SearchCheck],
['Taxation Services','Corporate tax, individual tax, indirect tax and municipal finance support.',Calculator],
['IT Systems Services','IT consulting, support, infrastructure, networks, cloud, cybersecurity, CCTV, business systems and staff training.',MonitorCog],
];
const values=['Professionalism','Integrity','Excellence','Commitment and Dedication','Continuous Improvement','Innovation','Teamwork','Client Satisfaction'];
export default function Home(){return <div id="home" className="bg-white">
<section className="pt-20 min-h-[720px] relative overflow-hidden bg-[#071d38]"><div className="absolute inset-0 opacity-45"><img src="/hero-office.jpg" className="w-full h-full object-cover object-right"/></div><div className="absolute inset-0 bg-gradient-to-r from-[#06172e] via-[#082c49]/95 to-[#008e9e]/35"/><div className="relative max-w-7xl mx-auto px-5 py-28 md:py-36"><div className="max-w-3xl"><p className="text-cyan-300 uppercase tracking-[.25em] text-xs font-bold mb-5">Professionalism · Integrity · Innovation · Excellence</p><h1 className="text-white text-5xl md:text-7xl font-extrabold leading-[1.02] mb-6">Audit. Advisory.<br/><span className="text-cyan-400">Taxation. ICT.</span><br/>Business Solutions.</h1><p className="text-slate-200 text-lg md:text-xl max-w-2xl leading-8 mb-8">High-quality professional services for municipalities, universities, TVET colleges, NPOs, departments, public entities and private companies.</p><div className="flex flex-wrap gap-3"><a href="#services" className="inline-flex items-center gap-2 bg-cyan-500 hover:bg-cyan-400 text-[#06172e] font-bold px-6 py-3.5 rounded-lg">Explore Services <ArrowRight size={17}/></a><a href="#contact" className="inline-flex items-center gap-2 border border-white/50 text-white px-6 py-3.5 rounded-lg hover:bg-white/10">Contact Us</a></div></div></div></section>
<section className="bg-[#0a3652] text-white"><div className="max-w-7xl mx-auto px-4 py-7 grid grid-cols-2 lg:grid-cols-4 gap-5">{[['100%','Black-Owned'],['2021','Established'],['SAICA & SARS','Registered'],['IIASA','Registered Auditors']].map(x=><div key={x[0]} className="border-l-2 border-cyan-400 pl-4"><strong className="text-xl md:text-2xl">{x[0]}</strong><p className="text-slate-300 text-sm">{x[1]}</p></div>)}</div></section>
<section id="about" className="py-20"><div className="max-w-7xl mx-auto px-5 grid lg:grid-cols-2 gap-14 items-center"><div className="rounded-3xl overflow-hidden shadow-2xl"><img src="/about-building.jpg" className="w-full h-[470px] object-cover"/></div><div><p className="text-cyan-600 uppercase tracking-widest text-xs font-bold">Company Introduction</p><h2 className="text-4xl md:text-5xl font-extrabold text-[#08213f] mt-3 mb-5">KAM Internal Auditors Inc.</h2><p className="text-slate-600 leading-7 mb-4">KAM Internal Auditors Inc. is a fast-growing 100% black-owned professional services firm established in 2021.</p><p className="text-slate-600 leading-7 mb-4">The company is registered with the South African Institute of Chartered Accountants (SAICA) and South African Revenue Services (SARS) as a Tax Practitioner. Our experienced internal auditors are registered members of the Institute of Internal Auditors South Africa (IIASA).</p><p className="text-slate-600 leading-7 mb-6">We provide high-quality audit, advisory, taxation, ICT, and business support services. Our commitment is built around professionalism, integrity, innovation, and excellence.</p><div className="grid sm:grid-cols-2 gap-3">{['Professional expertise','Client-centered service','Modern technology solutions','Public & private sector'].map(v=><div className="flex items-center gap-2 text-sm font-semibold text-[#08213f]" key={v}><CheckCircle2 size={18} className="text-cyan-500"/>{v}</div>)}</div></div></div></section>
<section id="services" className="py-20 bg-slate-50"><div className="max-w-7xl mx-auto px-5"><div className="text-center max-w-3xl mx-auto mb-12"><p className="text-cyan-600 uppercase tracking-widest text-xs font-bold">Our Services</p><h2 className="text-4xl md:text-5xl font-extrabold text-[#08213f] mt-3">Comprehensive Professional Solutions</h2></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">{services.map(([title,desc,Icon]:any)=><div key={title} className="bg-white rounded-2xl p-7 border border-slate-100 shadow-sm hover:-translate-y-1 hover:shadow-xl transition"><div className="w-12 h-12 rounded-xl bg-cyan-50 text-cyan-600 flex items-center justify-center mb-5"><Icon/></div><h3 className="font-bold text-xl text-[#08213f] mb-3">{title}</h3><p className="text-slate-600 text-sm leading-6">{desc}</p></div>)}</div></div></section>
<section id="vision" className="py-20 relative text-white overflow-hidden"><div className="absolute inset-0"><img src="/finance-bg.jpg" className="w-full h-full object-cover"/><div className="absolute inset-0 bg-[#06172e]/92"/></div><div className="relative max-w-7xl mx-auto px-5 grid lg:grid-cols-3 gap-8"><div className="p-7 border border-white/10 rounded-2xl bg-white/5"><Eye className="text-cyan-400 mb-4"/><h3 className="text-2xl font-bold mb-3">Our Vision</h3><p className="text-slate-300 leading-7">To become a leading and highly innovative audit, advisory, ICT, and business solutions provider recognized for excellence, professionalism, and client-centered service delivery.</p></div><div className="p-7 border border-white/10 rounded-2xl bg-white/5"><Target className="text-cyan-400 mb-4"/><h3 className="text-2xl font-bold mb-3">Our Mission</h3><p className="text-slate-300 leading-7">To deliver efficient, professional, and innovative solutions that help clients improve governance, strengthen internal controls, enhance operational performance, and embrace modern technology systems.</p></div><div className="p-7 border border-white/10 rounded-2xl bg-white/5"><Gem className="text-cyan-400 mb-4"/><h3 className="text-2xl font-bold mb-3">Core Values</h3><div className="grid grid-cols-2 gap-2 text-sm text-slate-300">{values.map(v=><span key={v}>• {v}</span>)}</div></div></div></section>
<section className="py-20"><div className="max-w-5xl mx-auto px-5 text-center"><p className="text-cyan-600 uppercase tracking-widest text-xs font-bold">Why Choose Us</p><h2 className="text-4xl font-extrabold text-[#08213f] my-4">Quality. Cost-Effective. Innovative.</h2><p className="text-slate-600 text-lg leading-8">KAM Internal Auditors Inc. delivers professional solutions tailored to each client. Experienced professionals combine technical expertise with modern technology to support operational excellence, accountability and sustainable growth.</p><a href="#contact" className="mt-8 inline-flex items-center gap-2 bg-[#08213f] text-white px-7 py-4 rounded-lg font-bold hover:bg-cyan-700">Request a Consultation <ArrowRight size={18}/></a></div></section>
</div>}
